linters:
  enable:
    - errcheck     # Detect unchecked errors
    - gosimple     # Simplify code
    - govet        # Examine Go source code and reports suspicious constructs
    - ineffassign  # Detect ineffectual assignments
    - staticcheck  # Go static analysis
    - typecheck    # Like the front-end of a Go compiler
    - unused       # Find unused variables, functions, constants
    - bodyclose    # Checks whether HTTP response bodies are closed
    - gocyclo      # Calculate cyclomatic complexity
    - gosec        # Inspects source code for security problems
    - misspell     # Find commonly misspelled words
    - revive       # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert    # Remove unnecessary type conversions
    - unparam      # Find unused function parameters

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unparam

run:
  timeout: 5m
  skip-dirs:
    - reports
    - custom_reports
    - short_flag_reports
    - resources 