version: "2"

linters:
  enable:
    - govet        # Examine Go source code and reports suspicious constructs
    - ineffassign  # Detect ineffectual assignments
    - staticcheck  # Go static analysis
    - unused       # Find unused variables, functions, constants
    - bodyclose    # Checks whether HTTP response bodies are closed
    - misspell     # Find commonly misspelled words
    - revive       # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert    # Remove unnecessary type conversions
    - unparam      # Find unused function parameters
    - gosec      
    - gocyclo
  disable:
    - errcheck
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
        - G204
        - G301
        - G304
run:
  timeout: 5m 