version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 15

severity:
  default: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

run:
  timeout: 5m
  tests: false
