# Configuration version for golangci-lint
version: "2"

linters:
  enable:
    - govet        # Examine Go source code and reports suspicious constructs
    - ineffassign  # Detect ineffectual assignments
    - staticcheck  # Go static analysis
    - unused       # Find unused variables, functions, constants
    - bodyclose    # Checks whether HTTP response bodies are closed
    - misspell     # Find commonly misspelled words
    - revive       # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert    # Remove unnecessary type conversions
    - unparam      # Find unused function parameters
    - gosec        # Inspects source code for security problems
    - gocyclo      # Calculates cyclomatic complexity of functions
  disable:
    - errcheck     # Disabled: checks for unchecked errors in code
  settings:
    gocyclo:
      min-complexity: 15  # Functions with complexity >= 15 will be reported
    gosec:
      excludes:
        - G104    # Excluded: errors unhandled
        - G204    # Excluded: subprocess launched with variable
        - G301    # Excluded: poor file permissions used
        - G304    # Excluded: file path provided as taint input
run:
  timeout: 5m     # Maximum time for analysis 