name: CI

on:
  push:
    branches: [ main, "**" ]  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Install dependencies
      run: go mod download
      
    - name: Install FFmpeg with debug support
      if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential yasm nasm libx264-dev libx265-dev
        
        # Clone FFmpeg from source
        git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg_source
        cd ffmpeg_source
        
        # Configure with debug and x265 support
        ./configure --enable-debug=3 --disable-stripping --enable-libx264 --enable-libx265 --enable-gpl
        
        # Build and install
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        
        # Verify installation
        ffmpeg -version

    - name: Run unit tests with coverage
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.txt
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m
        
    - name: Note on Cyclomatic Complexity
      run: |
        echo "Note: Cyclomatic complexity is checked in a separate workflow (gocyclo.yml)"
        echo "to ensure that no function exceeds the maximum allowed complexity of 15."

  dependency-check:
    name: Dependency Scanning
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Check vulnerable dependencies with Govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: '1.24'
        check-latest: true

    - name: Create dependency report with go list
      run: |
        mkdir -p reports
        
        # Create simple module dependency list
        echo "# Direct dependencies" > reports/deps-list.txt
        go list -m all >> reports/deps-list.txt
        
        # Create detailed package dependency list
        echo "# Package dependencies" > reports/deps-packages.txt
        go list -deps ./... >> reports/deps-packages.txt
        
        # Create dependency graph in DOT format
        echo "digraph G {" > reports/deps-graph.dot
        echo "  node [shape=box];" >> reports/deps-graph.dot
        go mod graph | sed 's/@/ /g' | awk '{print "  \"" $1 "\" -> \"" $2 "\""}' >> reports/deps-graph.dot
        echo "}" >> reports/deps-graph.dot

    - name: Upload dependency reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-reports
        path: reports/deps-* 